### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by protsenkovi** [ShadowOfDen/BigData#1]
Работает только часть скрипта. C чем могут быть связаны ошибки?
```
scala> :load script.scala
Loading script.scala...
import java.time.{LocalDate, LocalDateTime, Period}
import java.time.format.DateTimeFormatter
import org.apache.spark._
import org.apache.log4j.{Level, Logger}
import scala.collection.JavaConversions
import scala.collection.immutable.List
import java.io.{File, FileOutputStream, PrintWriter}
import java.time.temporal.ChronoUnit
import org.apache.commons.math3.util.FastMath.{pow, sqrt}
import runtime.ScalaRunTime.replStringOf
import runtime.ScalaRunTime.replStringOf
tripData: org.apache.spark.rdd.RDD[String] = trips.csv MapPartitionsRDD[3] at textFile at script.scala:52
tripsHeader: String = id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
trips: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[4] at filter at script.scala:55
res7: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[5] at map at script.scala:54
stationData: org.apache.spark.rdd.RDD[String] = stations.csv MapPartitionsRDD[7] at textFile at script.scala:52
stationsHeader: String = id,name,lat,long,dock_count,city,installation_date
stations: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[8] at filter at script.scala:55
res8: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[9] at map at script.scala:54
Trips Header
id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
Stations Header
id,name,lat,long,dock_count,city,installation_date
stationsIndexed: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[10] at keyBy at script.scala:53
res15: Array[(Int, String)] = Array((50,2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013), (51,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013), (52,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013), (53,5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013), (54,6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013), (55,7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013), (56,8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013), (57,9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013), (49,10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013), (49,11,MLK Library,37.335885,-121.88566000000002,19,S...
tripsByStartTerminals: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[11] at keyBy at script.scala:53
tripsByEndTerminals: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[12] at keyBy at script.scala:53
startTrips: org.apache.spark.rdd.RDD[(Int, (String, String))] = MapPartitionsRDD[15] at join at script.scala:55
endTrips: org.apache.spark.rdd.RDD[(Int, (String, String))] = MapPartitionsRDD[18] at join at script.scala:55
2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013
3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013
4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013
5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013
6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013
7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013
8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013
9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013
10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013
11,MLK Library,37.335885,-121.88566000000002,19,San Jose,8/6/2013
stations
Stations Indexed
(50,2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013)
(51,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013)
(52,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013)
(53,5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013)
(54,6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013)
(55,7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013)
(56,8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013)
(57,9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013)
(49,10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013)
(49,11,MLK Library,37.335885,-121.88566000000002,19,San Jose,8/6/2013)
defined class Station
defined class Trip
timeFormat: java.time.format.DateTimeFormatter = Value(MonthOfYear)'/'Value(DayOfMonth)'/'Value(YearOfEra,4,19,EXCEEDS_PAD)' 'Value(HourOfDay)':'Value(MinuteOfHour)
script.scala:63: error: type mismatch;
 found   : Char
 required: CharSequence
Error occurred in an application involving default arguments.
      startDate= LocalDateTime.parse(row(2), timeFormat),
                                        ^
script.scala:64: error: type mismatch;
 found   : Char
 required: String
Error occurred in an application involving default arguments.
      startStation=row(3),
                      ^
script.scala:66: error: type mismatch;
 found   : Char
 required: CharSequence
Error occurred in an application involving default arguments.
      endDate=LocalDateTime.parse(row(5), timeFormat),
                                     ^
script.scala:67: error: type mismatch;
 found   : Char
 required: String
Error occurred in an application involving default arguments.
      endStation=row(6),
                    ^
script.scala:70: error: type mismatch;
 found   : Char
 required: String
Error occurred in an application involving default arguments.
      subscriptionType=row(9),
                          ^
script.scala:71: error: type mismatch;
 found   : Char
 required: String
Error occurred in an application involving default arguments.
      zipCode=row(10)))
                 ^
trips internal:
script.scala:52: error: not found: value tripsInternal
println(tripsInternal.first)
        ^
script.scala:52: error: not found: value tripsInternal
println(tripsInternal.first.startDate)
        ^
script.scala:57: error: type mismatch;
 found   : Char
 required: String
    name=row(1),
            ^
script.scala:61: error: type mismatch;
 found   : Char
 required: String
    landmark=row(5),
                ^
script.scala:62: error: type mismatch;
 found   : Char
 required: String
    installation=row(6),
```

**Comment by ShadowOfDen** [comment]
> Работает только часть скрипта. C чем могут быть связаны ошибки?
> 
> ```
> scala> :load script.scala
> Loading script.scala...
> import java.time.{LocalDate, LocalDateTime, Period}
> import java.time.format.DateTimeFormatter
> import org.apache.spark._
> import org.apache.log4j.{Level, Logger}
> import scala.collection.JavaConversions
> import scala.collection.immutable.List
> import java.io.{File, FileOutputStream, PrintWriter}
> import java.time.temporal.ChronoUnit
> import org.apache.commons.math3.util.FastMath.{pow, sqrt}
> import runtime.ScalaRunTime.replStringOf
> import runtime.ScalaRunTime.replStringOf
> tripData: org.apache.spark.rdd.RDD[String] = trips.csv MapPartitionsRDD[3] at textFile at script.scala:52
> tripsHeader: String = id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
> trips: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[4] at filter at script.scala:55
> res7: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[5] at map at script.scala:54
> stationData: org.apache.spark.rdd.RDD[String] = stations.csv MapPartitionsRDD[7] at textFile at script.scala:52
> stationsHeader: String = id,name,lat,long,dock_count,city,installation_date
> stations: org.apache.spark.rdd.RDD[String] = MapPartitionsRDD[8] at filter at script.scala:55
> res8: org.apache.spark.rdd.RDD[Array[String]] = MapPartitionsRDD[9] at map at script.scala:54
> Trips Header
> id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
> Stations Header
> id,name,lat,long,dock_count,city,installation_date
> stationsIndexed: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[10] at keyBy at script.scala:53
> res15: Array[(Int, String)] = Array((50,2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013), (51,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013), (52,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013), (53,5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013), (54,6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013), (55,7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013), (56,8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013), (57,9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013), (49,10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013), (49,11,MLK Library,37.335885,-121.88566000000002,19,S...
> tripsByStartTerminals: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[11] at keyBy at script.scala:53
> tripsByEndTerminals: org.apache.spark.rdd.RDD[(Int, String)] = MapPartitionsRDD[12] at keyBy at script.scala:53
> startTrips: org.apache.spark.rdd.RDD[(Int, (String, String))] = MapPartitionsRDD[15] at join at script.scala:55
> endTrips: org.apache.spark.rdd.RDD[(Int, (String, String))] = MapPartitionsRDD[18] at join at script.scala:55
> 2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013
> 3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013
> 4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013
> 5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013
> 6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013
> 7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013
> 8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013
> 9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013
> 10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013
> 11,MLK Library,37.335885,-121.88566000000002,19,San Jose,8/6/2013
> stations
> Stations Indexed
> (50,2,San Jose Diridon Caltrain Station,37.329732,-121.90178200000001,27,San Jose,8/6/2013)
> (51,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013)
> (52,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013)
> (53,5,Adobe on Almaden,37.331415,-121.8932,19,San Jose,8/5/2013)
> (54,6,San Pedro Square,37.336721000000004,-121.894074,15,San Jose,8/7/2013)
> (55,7,Paseo de San Antonio,37.333798,-121.88694299999999,15,San Jose,8/7/2013)
> (56,8,San Salvador at 1st,37.330165,-121.88583100000001,15,San Jose,8/5/2013)
> (57,9,Japantown,37.348742,-121.89471499999999,15,San Jose,8/5/2013)
> (49,10,San Jose City Hall,37.337391,-121.886995,15,San Jose,8/6/2013)
> (49,11,MLK Library,37.335885,-121.88566000000002,19,San Jose,8/6/2013)
> defined class Station
> defined class Trip
> timeFormat: java.time.format.DateTimeFormatter = Value(MonthOfYear)'/'Value(DayOfMonth)'/'Value(YearOfEra,4,19,EXCEEDS_PAD)' 'Value(HourOfDay)':'Value(MinuteOfHour)
> script.scala:63: error: type mismatch;
>  found   : Char
>  required: CharSequence
> Error occurred in an application involving default arguments.
>       startDate= LocalDateTime.parse(row(2), timeFormat),
>                                         ^
> script.scala:64: error: type mismatch;
>  found   : Char
>  required: String
> Error occurred in an application involving default arguments.
>       startStation=row(3),
>                       ^
> script.scala:66: error: type mismatch;
>  found   : Char
>  required: CharSequence
> Error occurred in an application involving default arguments.
>       endDate=LocalDateTime.parse(row(5), timeFormat),
>                                      ^
> script.scala:67: error: type mismatch;
>  found   : Char
>  required: String
> Error occurred in an application involving default arguments.
>       endStation=row(6),
>                     ^
> script.scala:70: error: type mismatch;
>  found   : Char
>  required: String
> Error occurred in an application involving default arguments.
>       subscriptionType=row(9),
>                           ^
> script.scala:71: error: type mismatch;
>  found   : Char
>  required: String
> Error occurred in an application involving default arguments.
>       zipCode=row(10)))
>                  ^
> trips internal:
> script.scala:52: error: not found: value tripsInternal
> println(tripsInternal.first)
>         ^
> script.scala:52: error: not found: value tripsInternal
> println(tripsInternal.first.startDate)
>         ^
> script.scala:57: error: type mismatch;
>  found   : Char
>  required: String
>     name=row(1),
>             ^
> script.scala:61: error: type mismatch;
>  found   : Char
>  required: String
>     landmark=row(5),
>                 ^
> script.scala:62: error: type mismatch;
>  found   : Char
>  required: String
>     installation=row(6),
> ```

Очень странная ошибка, у меня такого не происходило. Почему-то происходит не соответствие типов переменных, хотя все типы были взяты из примера по репозиторию лабораторной работы.

**Comment by protsenkovi** [comment]
Она не связана с датами. Она связана с тем, что консоль spark-shell, которой я пользовался, загружает ваш код по строкам. Поэтому разбиение на слова, перенесённое на другую строку, не сохраняется в переменную trips.

https://github.com/ShadowOfDen/BigData/blob/1412aa5e36517204cee33e4f835018f4be99de48/Lab1/src/main/scala/Main.scala#L36
